### ISSUE TITLE
Jaipur geojson files issue

### ISSUE THREAD

**Issue by adivik2000** [datameet/Municipal_Spatial_Data#13]
I tried to use the geojson files for osm mapping but there seems to be a projection issue. Shapefiles are fine though. Should I fix them and do a PR?

**Comment by devdattaT** [comment]
Ah yes, they are in a different projection, and according to the Latest GeoJSON Specification they should be only in Lat-long (i.e. EPSG:4326). Please do send a PR.

**Comment by sandeepgadhwal** [comment]
I will check and update it.

**Comment by devdattaT** [comment]
I have updated the repo with the correct data from @sandeepgadhwal 's repo.
