### ISSUE TITLE
Pune municipal map 2017 onwards

### ISSUE THREAD

**Issue by answerquest** [datameet/Municipal_Spatial_Data#2]
please include this:
https://gist.github.com/answerquest/db11b5c7be7e00765ae33152124aba1e
(see comment in there for related info)

**Comment by devdattaT** [comment]
Thanks Nikhil!

**Comment by answerquest** [comment]
Hi, I've updated documentation for 3 electoral ward maps of Pune: pre-2012, 2012-17, 2017-onwards. https://github.com/datameet-pune/datameet-pune.github.io/tree/master/maps. Should close some loose ends as far as electoral ward maps is concerned.
