### ISSUE TITLE
Kolkata Boundries and wardfiles are issing

### ISSUE THREAD

**Issue by Akhandalamani** [datameet/Municipal_Spatial_Data#21]
plz add kolkata boundaries shape files and neighborhood and ward files

**Comment by thejeshgn** [comment]
Some info is here
https://www.kmcgov.in/KMCPortal/jsp/KMCMap.jsp
https://www.kmcgov.in/KMCPortal/jsp/kolkata_City_Map.html
https://www.kmcgov.in/KMCPortal/downloads/Borough_Wise_Detailed_Map.pdf

We need to digitize it

**Comment by Akhandalamani** [comment]
thanks for response

**Comment by answerquest** [comment]
Update: someone just shared a shapefile on datameet mailling list. See: https://groups.google.com/d/msg/datameet/k7Hp9jEDRTk/H66HNdNiBAAJ

144 polygons, but 3 entries have blank WARD value and are invisible / don't have any valid shape.
Others numbered 1 to 141. (column: WARD)
Other attributes: shape_Leng, shape_Area

Screenshot:
![kolkata-shapefile](https://user-images.githubusercontent.com/9089552/46868635-9f460980-ce46-11e8-9157-2f0237e71081.png)

Note: ward 136 has typo, stored as `136/`

**Comment by devdattaT** [comment]
I have added this data in the Repo.
