### ISSUE TITLE
Either file is password protected or corrupt

### ISSUE THREAD

**Issue by accessible** [datameet/Municipal_Spatial_Data#26]
https://github.com/datameet/Municipal_Spatial_Data/archive/master.zip

Either file is password protected or corrupt

**Comment by devdattaT** [comment]
How big was the filw when you downloaded it? it should be 35.3 MB. if i it's not, then can you try downloading it over a stable internet connection?

**Comment by accessible** [comment]
it is 70 mb

**Comment by devdattaT** [comment]
This zip is created by Github, and has no password.

If the file has a weird size like this, mostly the internet connection, or browser are not functioning properly. Try downloading it again, using a modern browser, and failing that, you can click on the particular file that you need, and view it in raw mode
