### ISSUE TITLE
I want shapefile of below mentioned States

### ISSUE THREAD

**Issue by ghost** [datameet/Municipal_Spatial_Data#30]
Hi,
Here I mentioned some popular cities name for my work purpose if you have shapefiles on that cites/states kindley update on that.

**Andhra Pradesh
Gujarat
Haryana
Kerala
Madhya Pradesh
Navi Mumbai
Uttar Pradesh
West Bengal**

**Comment by thejeshgn** [comment]
Check  https://github.com/datameet/maps
