### ISSUE TITLE
Adopt `CC-by 4.0` license to be compatible with Government Open Data License

### ISSUE THREAD

**Issue by planemad** [datameet/Municipal_Spatial_Data#39]
This was already done on the datameet/maps repository. Discussion and rationale here https://github.com/datameet/maps/issues/56 .

We have already had interest from research scholars to use the /maps data after the CC-by license change. The ward boundaries are often requested on the mailing list, and relicensing this data will allow greater reuse and contributions back to this repository.

Tagging all repo contributors for approval: 
- [x] @devdattaT 
- [x] @thejeshgn 
- [x] @sandeepgadhwal
- [x] @adivik2000
- [x] @kaizer1v 
- [x] @nishadhka 

Please feel free to post your thoughts if you feel this relicensing should not be done.

**Comment by thejeshgn** [comment]
👍🏼

**Comment by devdattaT** [comment]
I agree with this change.

**Comment by nishadhka** [comment]
I am Okay with the change.

**Comment by adivik2000** [comment]
👍🏼

**Comment by kaizer1v** [comment]
+1 to this 👍

**Comment by thejeshgn** [comment]
@sandeepgadhwal can you respond, please.

**Comment by sandeepgadhwal** [comment]
I agree with this change.

**Comment by thejeshgn** [comment]
@planemad you can go ahead with the update.
