### ISSUE TITLE
Please provide shapefile of Kochi

### ISSUE THREAD

**Issue by nnnils** [datameet/Municipal_Spatial_Data#45]
Need administrative boundary of Kochi municipality

**Comment by thejeshgn** [comment]
@devdattaT can I pull from 
- Source https://opensdi.kerala.gov.in/maps/new?layer=geonode:KSUDP_KCH_Ward_Boundary&view=True
- Layer https://opensdi.kerala.gov.in/capabilities/layer/72/

**Comment by devdattaT** [comment]
@thejeshgn 
If you can pull it please do. 
I briefly tried, but could not get it in vector format. I will have time at the end of the week to look at this. So if you can get it before that, we should definitely include it.
