### ISSUE TITLE
BBMP (Bengaluru) shp file is 6 years old

### ISSUE THREAD

**Issue by sanjmeh** [datameet/Municipal_Spatial_Data#49]
As BBMP has now redfined boundaries in 2022, we would need the new shp files for all wards.
Are the new shp files getting prepared or are already launched somewhere else?

**Comment by devdattaT** [comment]
No one is actively working on this; 
But if you have seen an online interactive map with the latest boundaries, I could try to see if we can extract it.

**Comment by devdattaT** [comment]
@sanjmeh You could download it from here: https://github.com/statsofindia/bbmp-delimitation-2022

**Comment by devdattaT** [comment]
Is this what you need ?
https://gist.github.com/devdattaT/021f8ed67ad52dbfa2ea1dfbc4dce42f
